Project Day 2: Transactions and queries
jonas-45/vet-clinic-database-postgreSql pull request #2
Opened 2023-04-04 20:48 UTC by jonas-45

<h3>In this milestone, SQL transactions, and aggregates were implemented in queries. The implementations are given below;</h3>

- [ ] Data was added to the animal's table
![Screenshot2](https://user-images.githubusercontent.com/113814214/229915920-f56454c9-adff-4cac-a652-8ade7ddabffe.png)

- [ ] Inside a transaction, the animal's table was updated by setting the species column to unspecified and then rolling back the change.
![Screenshot1](https://user-images.githubusercontent.com/113814214/229915877-b109178d-fe2b-4efe-80ee-75717967ebe6.png)

- [ ] Inside a transaction, the animal's table was updated by setting the species column to digimon for all animals that have a name ending in 'mon' and also setting species to pokemon for all animals that don't have species already set.
![Screenshot3](https://user-images.githubusercontent.com/113814214/229916020-1de14b20-cbb4-4037-8b52-c4020baa23d4.png)

- [ ] All the data in the table was deleted and rolled back in a transaction
![Screenshot4](https://user-images.githubusercontent.com/113814214/229916103-e7e4a053-8393-4624-838d-00a6f1d20dc3.png)

- [ ] In a transaction, specific animals were deleted, created a savepoint, updated the animals table and rolled back to the savepoint
![Screenshot5](https://user-images.githubusercontent.com/113814214/229916170-5670287c-27ab-4d46-a295-8db95edb9d46.png)

<h3>The following questions were answered with queries</h3>

- [ ] How many animals are there?
![Screenshot6](https://user-images.githubusercontent.com/113814214/229916291-33162734-de7a-4a32-b19f-c49d30c4fa0a.png)

- [ ] How many animals have never tried to escape?
![Screenshot7](https://user-images.githubusercontent.com/113814214/229916356-6b8eed17-e6f5-4c30-a9c7-aacefb607939.png)

- [ ] What is the average weight of animals?
![Screenshot8](https://user-images.githubusercontent.com/113814214/229916473-f821f602-43cc-4aa6-bb01-11556ba94746.png)

- [ ] Who escapes the most, neutered or not neutered animals?
![Screenshot9](https://user-images.githubusercontent.com/113814214/229916733-d2216e3d-2605-4dba-8b60-493eaed8af06.png)

- [ ] What is the minimum and maximum weight of each type of animal?
![Screenshot10](https://user-images.githubusercontent.com/113814214/229916795-28c22f6d-4a59-48f0-a771-8ed34641440d.png)

- [ ] What is the average number of escape attempts per animal type of those born between 1990 and 2000?
![Screenshot11](https://user-images.githubusercontent.com/113814214/229916951-c9e33d70-373c-4d34-8be0-85de36367eb8.png)

2023-04-04 21:03 UTC, brytebee requested changes
Hi, @jonas-45👋,

##

### Highlights💡
- Good commit message.✔️ 
- Good PR Summary.✔️
- Great DB design.✔️
- App functions as it should.✔️

##

Good job so far coming so far with the progress you've made! 💪💪
 
However, there are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/VL48WGMDjD64umCEkv/giphy.gif)

# Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Please, remember to tag me in your question so I can receive the notification.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @brytebee in your question so I can receive the notification.
### _**Use @brytebee on slack for faster responses.**_


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-04 21:03 UTC, brytebee commented on queries.sql
> +COMMIT;
For this transaction and others, after every activity you are required to verify the activity worked and when there is a rollback or commit to also verify.

![image](https://user-images.githubusercontent.com/27709832/229920081-2f752346-c8dc-436b-a666-ae0578332daa.png)

All verification should be made as shown below.

SELECT * FROM animals;
(select all from the specified table in the case above the animals table.)

2023-04-04 21:03 UTC, brytebee commented on queries.sql
> +ROLLBACK;
Here.

2023-04-04 21:03 UTC, brytebee commented on queries.sql
> +COMMIT;
Here too. Kindly look through the instruction for other verify points.

2023-04-04 22:58 UTC, OyePriscilla requested changes
Hi @jonas-45 👏 👏 , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![so-close-so-close-seth-meyers](https://user-images.githubusercontent.com/103386183/196425724-8ca5825c-b02a-4983-b976-4bd0a2f70f9a.gif)

 ## Highlights
Use database transactions ✔️ 
Modify and delete data in SQL ✔️ 
Create queries to answer some questions in transactions ✔️ 
Made some of the required changes ✔️ 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-04 22:58 UTC, OyePriscilla commented on queries.sql
> +COMMIT;
- [ ] Please as raised earlier, kindly verify (**as you rightly did for others**) that after the `ROLLBACK` in line 42 and `COMMIT` in line 44 that all records in animal table still exist. 

<img width="576" alt="Untitled" src="https://user-images.githubusercontent.com/103386183/229939847-2517c98b-1483-441c-af32-708af91e2724.png">

2023-04-05 00:50 UTC, jonas-45 commented
@OyePriscilla thanks for your time and effort in reviewing my work. Please I implemented all the changes requested by @brytebee. What you are referring to was corrected in line 31. 
![Screenshotv](https://user-images.githubusercontent.com/113814214/229953609-14f44263-95ee-43d6-8824-19c5149280b6.png)

We are not required to verify change in line 42 and 44;
![Screenshot 2023-04-05 004732](https://user-images.githubusercontent.com/113814214/229953654-13ed9a0a-551b-499c-aa33-1d801d78413b.png)

2023-04-05 02:12 UTC, Reem-lab approved these changes
# Hi @jonas-45,👋🏻👋🏻

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 🔥🔥💯💯
<img src="https://media2.giphy.com/media/3o6fJ1BM7R2EBRDnxK/giphy.gif"/>

## Highlights 🔥🔥🔥🔥
- Followed Gitflow ✅
- No Linters error 🤩🔥💯
- Great working on the functionality 🔥🔥




## Optional suggestions



_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-05 11:36 UTC, merged